include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode: true
#   excludes:
#     - path/to/excluded/files/**
linter:
  rules:
    always_declare_return_types: true
    camel_case_types: true
    empty_constructor_bodies: true
    annotate_overrides: true
    constant_identifier_names: true
    slash_for_doc_comments: true
    sort_constructors_first: true
    unnecessary_brace_in_string_interp: true
    omit_local_variable_types: false
    avoid_init_to_null: false